src/library/urls.py
from django.urls import path
from .views import *
app_name='library'

urlpatterns=[
    path('<slug:slug>',pdf_view,name='pdf_view'),
    path('reciveData/',reciveData,name='reciveData'),
    path('filter_books/<str:str>',filter_books,name='filter_books'),
    path('search/',search,name='search'),
    path('create_commint/',create_commint,name='create_commint'),
    path('delete_commint/',delete_commint,name='delete_commint'),
    path('add_book/',addbook,name='addbook'),

]

src/profiles/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name='profiles'
urlpatterns = [
    path('<slug:slug>',profile_view,name='profile_view'),
    path('<slug:slug>/allBooks',allBooks,name='allBooks'),
    path('<slug:slug>/editprofile',editprofile,name='editprofile'),
    path('<slug:slug>/edit_book/',editbookforms,name='editbookforms'),
    path('<slug:slug>/delet_Book/',deleteBook,name='deleteBook'),
    path('SignUp/',signup,name='signup'),
    path('sendmessage/',sendmessage,name='sendmessage'),

   


    
    
    
    
]

src/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home ,name='home'),
    path('library/',include('library.urls',namespace='library')),
    path('profile/',include('profiles.urls',namespace='profile')),
    path('accounts/',include('django.contrib.auth.urls')),

     #____Rest Password_____#
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),name='password_reset'),
    path('pasword_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name = 'registration/password_reset_complete.html'),name='Password_reset_complete')
    
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from .utils import slugid
import datetime
class Profile(models.Model):
    name=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='name')
    first_name=models.CharField(max_length=20, null=True ,blank=True)
    last_name=models.CharField(max_length=20, null=True ,blank=True)
    avatar=models.ImageField(upload_to='media')
    created=models.DateTimeField(default=datetime.datetime.now)
    describtion=models.TextField(blank=True)
    slug=models.SlugField(blank=True)


    def __str__(self):
        return str(self.name)
    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug=slugify(slugid)
        super(Profile,self).save(*args,**kwargs)

    def num_book(self):
        return self.publisher.all().count()
            

src/profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
class EditProfile(forms.ModelForm):
    
    class Meta:
        model=Profile
        fields=['first_name','last_name','avatar','describtion']
        #widgets={'avatar':forms.(attrs={'class':'profile__image'}),}

src/profiles/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import *
from library.models import Library
from .forms import EditProfile
from library.forms import EditBook
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login,authenticate
from django.core.mail import send_mail

@login_required
def profile_view(request,slug):
    obj=Profile.objects.get(slug=slug)
    return render(request,'sss.html',{'obj':obj})

def allBooks(request,slug):
    profile=Profile.objects.get(slug=slug)
    all=Library.objects.filter(publisher=profile)
    return render(request,'allBook.html',{'obj':all})

#_________________________________________________#
@login_required
def editprofile(request,slug):
    profile=Profile.objects.get(slug=slug)
    autin=Profile.objects.get(name=request.user)
    if profile ==autin:
        if request.method =='POST':
            form=EditProfile(request.POST,request.FILES,instance=profile)
            if form.is_valid():
                instance=form.save(commit=False)
                instance.name=request.user
                instance.save()
                return redirect('profile:profile_view',slug)
        else:
            form=EditProfile(instance=profile)
            return render(request,'editprofile.html',{'form':form})
    else :
        return HttpResponse('ماكو هيج كلاوات ترة ')

#____________________________#
@login_required
def editbookforms(request,slug):
    
    book=Library.objects.get(slug=slug)
    profile=Profile.objects.get(name=request.user)
    if request.method =='POST':
        form=EditBook(request.POST ,request.FILES,instance=book)
        if form.is_valid:
            instance=form.save(commit=False)
            instance.publisher=profile
            form.save()
            return redirect('profile:allBooks',profile.slug)
    else:
        form=EditBook(instance=book)
        return render(request,'editBook.html',{
          'form':form,
          
        })
@login_required
def deleteBook(request,slug):
    book=Library.objects.get(slug=slug)
    uuser=Profile.objects.get(name=request.user)
    if book.publisher == uuser:
        book.delete()
        return redirect('profile:allBooks',book.publisher.slug)
    else:
        return HttpResponse('اكعد راحة عمو لا تلعب  ')

def signup(request):
    if request.method =='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            
            username=form.cleaned_data['username']
            password=form.cleaned_data['password1']
            form.save()
            user=authenticate(username=username,password=password)
            login(request,user) 
            new_user=User.objects.all()
            getUser=User.objects.get(pk=len(new_user))
            getProfile=Profile.objects.get(name=getUser)
            return redirect('profile:profile_view',getProfile.slug)
    else:
        form=UserCreationForm()
    return render(request,'registration/signup.html',{'form':form})

def sendmessage(request):
    send_mail(
    'the subject',
    'the content of message',
    #the sender 
    'alaziiammar10@gmail.com',
    #the reciver
    ['alaziiammar@gmail.com'],
    fail_silently=False
    )
    return render(request,'email_sended.html')

src/profiles/templates/allBook.html
{% extends 'main/baseallBook.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet icon" href="{% static 'css/allBookStyle.css' %}">
{% endblock head %}
{% block title %}
Books
{% endblock title %}
{% block body %}
<div class="cover">
    <div class="wepper">
        <h2>You can add a book by clicking on <a href="/library/add_book/">Add Book</a> </h2>
        {% for i in obj %}
        <div class="card__book">
            <div class="title__book">
                <div class="image__book">
                    {% if i.image %}
                    <img src="{{i.image.url}}" alt="" class="image__book">
                    {% else %}
                    <img src="{% static 'img/avatar3.png' %} alt="" class="image__book">
                    {% endif %}
                </div>
                <div class="collecter">
                    <div class="auther__book">
                        <a href="{% url 'profile:profile_view' i.publisher.slug %}">{{i.publisher}}</a>
                    </div>
                    <div class="created__book">
                        <p>{{i.published|date:"Y , M , D"}}</p>
                    </div>
                </div>
            </div>
            <!-- book information -->
           
            <div class="discription__address">
                <h5><a href="">{{i.book_name}}</a></h5>
                <div class="discription__book">{{i.Description}}</div>
            </div>
            
            <!--end book information-->
            {% if i.publisher.name == request.user %}
            <div class="update__book">
                <a href="{% url 'profile:editbookforms' i.slug %}"><i class="fas fa-pencil"></i></a> 
            </div>
            <div class="delete__book">
                <a href="{% url 'profile:deleteBook' i.slug %}"><i class="fas fa-trash"></i></a>    
            </div>
            {% endif %}
        </div> 
        
        {% endfor %}   
    </div>
</div>
{% endblock body %}

{% block script %}
<script>

</script>

{% endblock script %}

src/profiles/templates/editBook.html
{% extends 'main/baseProfile.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/editprofile.css' %}">
{% endblock head %}
{% block title %}
Edit Profile
{% endblock title %}

{% block body %}
<section class="cover_forms" >
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="firstName">Book name: {% render_field form.book_name|add_class:'firstName renderfirstName'%}</div>
       
        <div class="describtion">Description :{% render_field form.Description|add_class:'describtion renderdescribtion'%}</div>
        <div class="avatar">Image :{% render_field form.image|add_class:'avatar renderavatar'%}</div>
       
        <button class="save" type="submit">Save</button>
        </form>
</section>


{% endblock body %}

src/profiles/templates/editprofile.html
{% extends 'main/baseProfile.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/editprofile.css' %}">
{% endblock head %}
{% block title %}
Edit Profile
{% endblock title %}

{% block body %}
<section class="cover_forms" >
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="firstName">First Name : {% render_field form.first_name|add_class:'firstName renderfirstName'%}</div>
        <div class="lastName">Last Name : {% render_field form.last_name|add_class:'lastName renderlastName'%}</div>
        <div class="describtion">Description :{% render_field form.describtion|add_class:'describtion renderdescribtion'%}</div>
        <div class="avatar">Image :{% render_field form.avatar|add_class:'avatar renderavatar'%}</div>
       
        <button class="save" type="submit">Save</button>
        </form>
</section>

{% endblock body %}

src/profiles/templates/email_sended.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>the message sended</p>
</body>
</html>

src/profiles/templates/sss.html
{% extends 'main/baseProfile.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/profileStyle.css' %}">
{% endblock head %}
{%  block title %}
Profile
{%  endblock title %}


{%  block body %}

<div class="background">
    <div class="profile">
        <div class="image">
            {% if obj.avatar %}
            <img src="{{obj.avatar.url}}" alt="" class="profile__image">
            {% else  %}
            <img src="{% static 'img/avatar.png' %}" alt="" class="profile__image">
            {% endif %}
        </div>
        <div class="infomration">
            <div class="information__profile">
                <div class="username" >
                    {% if obj.first_name and obj.last_name %}
                    <div>{{obj.first_name}}&ThinSpace;{{obj.last_name}}</div>
                    {% else %}
                    <div>none</div>
                    {% endif %}
                    {% if obj.slug == objects.slug %}
                    <a href="{% url 'profile:editprofile' obj.slug %}" class="update"><i class="fas fa-pencil"></i></a>
                    {% endif %}
                </div>
                <div class="discription">{{obj.describtion|truncatechars:230}}</div>
                <div class="number_book"><a href="{% url 'profile:allBooks' obj.slug %}"><i class="fas fa-books"></i>
                    The number of books :
                      {{obj.num_book}}
                    </a></div>
                <div class="created"><i class="far fa-clock"></i> The date of join :{{obj.created|date:" Y , b , D "}}</div>
                
                
            </div>
        </div>
            
</div>
</div>
{%  endblock body %}