src/library/urls.py
from django.urls import path
from .views import *
app_name='library'

urlpatterns=[
    path('<slug:slug>',pdf_view,name='pdf_view'),
    path('reciveData/',reciveData,name='reciveData'),
    path('filter_books/<str:str>',filter_books,name='filter_books'),
    path('search/',search,name='search'),
    path('create_commint/',create_commint,name='create_commint'),
    path('delete_commint/',delete_commint,name='delete_commint'),
    path('add_book/',addbook,name='addbook'),

]

src/profiles/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name='profiles'
urlpatterns = [
    path('<slug:slug>',profile_view,name='profile_view'),
    path('<slug:slug>/allBooks',allBooks,name='allBooks'),
    path('<slug:slug>/editprofile',editprofile,name='editprofile'),
    path('<slug:slug>/edit_book/',editbookforms,name='editbookforms'),
    path('<slug:slug>/delet_Book/',deleteBook,name='deleteBook'),
    path('SignUp/',signup,name='signup'),
    path('sendmessage/',sendmessage,name='sendmessage'),

   


    
    
    
    
]

src/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home ,name='home'),
    path('library/',include('library.urls',namespace='library')),
    path('profile/',include('profiles.urls',namespace='profile')),
    path('accounts/',include('django.contrib.auth.urls')),

     #____Rest Password_____#
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),name='password_reset'),
    path('pasword_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name = 'registration/password_reset_complete.html'),name='Password_reset_complete')
    
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet icon" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet icon" href="{% static 'css/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>

    </title>
</head>
<body>
    <!--navbar-->
    <nav class="navbar">
        <div class="nav__container">
            <div class="logo" id="logo">Library</div>
            <div class="list">
                <div class="span">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            <ul class="options" id="options">
                <li>
                    <!--selctor-->
                    <div class="base">
                        <div class="content-optins">Last reading


                            <div class="all-option" id="all-option">
                                <div class="optin1">
                                    {% if history %}
                                    {% for i in history reversed %}
                                    <a href="{% url 'library:pdf_view' i.slug %}">
                                        <div class="card-option">
                                            <div class="info_option">
                                                {% if i.image %}
                                            <img src="{{i.image.url}}" alt="" class="image-option">
                                            {% else %}
                                            <img src="{% static 'img/avatar3.png' %}" alt="" class="image-option">
                                            {% endif %}
                                            <h3 class="title-option">{{i.book_name|truncatechars:20}}</h3>
                                            </div>
                                            
                                        </div>
                                    </a>
                                    {% endfor %}
                                    {% endif %}
                            </div>
                            </div>


                        </div>
                        <div class="arrow"><i class="fas fa-arrow-alt-circle-down"></i></div>
                    </div>
                    <!--end selector-->
                </li>
                <li><a href="{% url 'library:filter_books' 'Romance' %}">Romance</a></li>
                <li><a href="{% url 'library:filter_books' 'Cookbooks' %}">Cookbooks</a></li>
                <li><a href="{% url 'library:filter_books' 'Travel' %}">Travel</a></li>
                <li><a href="{% url 'library:filter_books' 'Short stories' %}">Short stories</a></li>
                {% if request.user.is_authenticated %}
                <li class="profile"><a href="{% url 'profile:profile_view' objects.slug %}">{{objects}} <i class="far fa-user"></i></a></li>
                {% else %}
                <li class="profile"><a href="{% url 'login' %}">{{objects}} <i class="far fa-user"></i></a></li>
                {% endif %}
            </ul>

        </div>
        </div>
    </nav>
    <div class="hero__container">
        <div class="hero__serach">
            <form action="{% url 'library:search' %}" metod="get" >
              {% csrf_token %}
              <input class="input" type="search" name="search" placeholder="Enter the name of the book" >
               <button class="button" type="submit" ><i class="far fa-search"></i></button>
            </form>
        </div>
    </div>

    <!--card section-->
    <div class="card__container">
      {% if x %}
      <p class="erorrMessage">{{x}}</p>
      {% endif %}
        <div class="wepper">
            <div class="card__wepper">

                {% for i in obj %}
                <div class="card">
                    <div class="img">
                       {% if not i.image %}
                       <img src="{% static 'img/IMG20201126180222.jpg' %}" alt="">
                       {% else %}
                       <img src={{i.image.url}} alt="">
                       {%endif%}
                    </div>

                  <div class="card__back">
                    <div class="user_info">
                        <div class="user_name">
                            {% if i.publisher.avatar %}
                            <img src="{{i.publisher.avatar.url}}" alt="">
                            {% else %}
                            <img src="{% static 'img/avatar.png' %}" alt="">
                            {% endif %}
                            <h5><a href="{% url 'profile:profile_view' i.publisher.slug %}">{{i.publisher}}</a></h5>
                        </div>
                        <div class="created">
                            <p>{{i.published}}</p>
                        </div>
                        
                     </div>
                     <div class="box">
                        <h3>{{i.book_name}}</h3>
                     <p>{{i.Description|truncatechars:200}}</p>
                     <div class="card__veiw__commint">
                        <div class="view"><i class="fas fa-eye"></i><div>{{i.all_views}}</div></div>
                        <div class="commint"><i class="far fa-comment-dots"></i><div>{{i.number_commint}}</div></div>
                        <div class="read">

                                <a href="{% url 'library:pdf_view' i.slug %}"
                                  class="AddViewer" data-you={{request.user}}
                                   data-slug={{i.slug}} data-action="add"
                                    >
                                <i class="far fa-book-open"></i></a>

                            </div>
                     </div>
                  </div>

                  </div>
               
                  <div class="commint_back ">
                      <div class="close">
                        <i class="fas fa-times"></i>
                      </div>
                       
                      <div class="commints">
                          {% for j in i.all_commint reversed %}
                          <!--CREATE COMMINT-->
                          <div class="one__commint">
                            <div class="user_name__commint">
                                <div class="user">
                                    {% if j.user.avatar %}
                                <img  src="{{j.user.avatar.url}}" alt="">
                                {% else %}
                                <img src="{% static 'img/avatar.png' %}" alt="">
                                {% endif %}
                                <h5><a href="{% url 'profile:profile_view' j.user.slug %}">{{j.user}}</a></h5>
                            </div>
                            <div class="delete_commint">
                                {% if request.user == j.user.name %}
                                <form class="delete" action="{% url 'library:delete_commint'%}" method="post" >
                                    {% csrf_token %}
                                    <input type="hidden" name="key" value={{j.id}}>
                                    <button type="submit" ><i class="fad fa-trash"></i></button>
                                </form>
                                
                                {% endif %}
                            </div>
                                
                            </div>
                         <p class="content__commint  {{i.slug}}">
                             {{j.content}}
                         </p>
                         <div class="created__commint">
                            <p>{{j.created}}</p>
                        </div> 
                        </div>  
                        <!--END CREATE COMMINT-->  
                        {% endfor %}                      
                      </div>
                    
                    
                      <div class="createcommint">
                        <form  class="forms" action="{% url 'library:create_commint' %}" method="post" >
                            {% csrf_token %}
                            <input  type="hidden" name="slug" value={{i.slug}}>
                            <input  class="commint__input" name="commint" type="text" placeholder="Leave a comment">
                            <button  type="submit" class="commint__button" >Send</button>
                        </form>
                      </div>

                  </div>
                  </div>
                 {% endfor %}
          
               </div>
           </div>
        </div>
    <!--pagination section-->
    {% if obj.has_other_pages %}
	<nav class="pagination">
	<ul class="pagination__list">
        {% if obj.has_previous %}
	    <li class="priviuose"><a href="?page={{obj.previous_page_number}}">priviuose</a> </li>
        {% endif %}

        {% for page in obj.paginator.page_range %}
        {% if obj.number == page %}
        <li class="tow active">{{page}}</li>
        {% else %}
        <li class="three"><a href="?page={{page}}">{{page}}</a></li>
        {% endif %}
        {% endfor %}

        {% if obj.has_next %}
        <li class="next"><a href="?page={{obj.next_page_number}}">next</a></li>
        {% endif %}
	</ul>
    </nav>
    {% endif %}
    <!--end pagination section-->
<!--footer section-->
<section class="footer">
   <div class="footer__container">
   <div class="footer__about">
      <div class="about">
         <h1>Title</h1>
         <p>escripdsfghi sdijgsdkjg dsgjsdkgj dogjdsgj dsgjdksg dgjdsgj dkgjdkgj sdkgjdskg  dkgjdskg dsgjdskgj dgjsdgj sgjgj dkgjgk  dskgjdlkg dskgjdkg dkgdlkg dkgjsdjglksdj dsgflsdkgj dkgsdlkg dlkgdslg tion</p>
      </div>
      <div class="contact">
          <h1>contact </h1>
          <div class="span">
            <span><a href="#"><i class="fab fa-twitter"></i></a></span>
            <span><a href="#"><i class="fab fa-facebook"></i></a></span>
            <span><a href=""><i class="fab fa-linkedin"></i></a></span>
            <span><a href=""><i class="fab fa-instagram"></i></a></span>
          </div>
      </div>
   </div>
   <div class="footer__copyright">
      &copy; 2020 Copyright :&nbsp;<a href="http://ammaralazie.pythonanywhere.com">ammaralazie.pythonanywhere.com</a>
   </div>
</div>
</section>
<!-- end footer section-->

<script>
usr='{{request.user}}'
</script>
<script >
  //docs.dajngo project AJAX
  function getToken(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
//انضيف هذا المتغير الى ملف الجافا سكربت حتى نححق مطالب سي اس ا اس ار اف تكوين
const csrftoken = getToken('csrftoken');
</script>
<script src={% static 'js/mainjs.js' %}></script>
<script src={% static 'js/show.js' %}></script>
<script src={% static 'js/close.js' %}></script>
<script src={% static 'js/commintSend.js' %}></script>
<script src={% static 'js/deleteCommint.js' %}></script>
<script src={% static 'js/showOption.js' %}></script>
</body>
</html>